---
- name: "Bluetooth - Check if Bluetooth is already in menu bar"
  command: "defaults read com.apple.systemuiserver menuExtras"
  register: result
  changed_when: False

- name: "Bluetooth - Show Bluetooth in menu bar"
  osx_defaults: { domain: 'com.apple.systemuiserver', key: 'menuExtras', type: array, array_add: "true", value: [ "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" ] }
  when: Bluetooth.ShowInMenuBar is defined and Bluetooth.ShowInMenuBar == "true" and 'Bluetooth.menu' not in result.stdout
  notify: restart MenuBar

# TODO: support remoce from menubar
