---
- { include: app-store.yml, tags: "app-store" }
- { include: dashboard.yml, tags: "dashboard" }
- { include: date-time.yml, tags: "date-time" }
- { include: displays.yml, tags: "displays" }
- { include: dock.yml, tags: "dock" }
- { include: general.yml, tags: "general" }
- { include: icloud.yml, tags: "icloud" }
- { include: keyboard.yml, tags: "keyboard" }
- { include: language-region.yml, tags: "language-region" }
- { include: mission-control.yml, tags: "mission-control" }